<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--Родительский pom-->
    <parent>
        <groupId>qa</groupId>
        <artifactId>pom</artifactId>
        <version>1.9</version>
    </parent>

    <!--Версия проекта-->
    <artifactId>qa-expertise</artifactId>

    <!-- Внутренние репозитории -->
    <repositories>
        <repository>
            <id>pom</id>
            <url>https://modeus-gitlab.custis.ru/api/v4/projects/697/packages/maven</url>
        </repository>
    </repositories>

    <build>
        <defaultGoal>exec:exec</defaultGoal>

        <!-- Плагины -->
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <cleanupDaemonThreads>false</cleanupDaemonThreads>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>

        <!--Ресурсы-->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>