<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--Переменные-->
    <properties>
        <project.version>1.0.0</project.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <j2html.version>1.6.0</j2html.version>
        <jackson.version>2.17.2</jackson.version>
        <javax.version>1</javax.version>
        <snakeyaml.version>2.2</snakeyaml.version>
        <poi.version>5.4.1</poi.version>
        <log4j.version>2.19.0</log4j.version>
        <json-simple.version>1.1.1</json-simple.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <build.target>25</build.target>
        <java.version>25</java.version>
    </properties>

    <!--Зависимости проекта-->
    <dependencies>
        <dependency>
            <groupId>com.j2html</groupId>
            <artifactId>j2html</artifactId>
            <version>${j2html.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>${javax.version}</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>${snakeyaml.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>${json-simple.version}</version>
        </dependency>
    </dependencies>

    <!--Версия проекта-->
    <artifactId>qa-expertise</artifactId>
    <groupId>MostHappyCougar</groupId>
    <version>${project.version}</version>
    <build>
        <defaultGoal>exec:exec</defaultGoal>
        <!--Плагины-->
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <cleanupDaemonThreads>false</cleanupDaemonThreads>
                    <executable>target\qa_expertise-1.0.jar</executable>
                    <mainClass>Main</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <source>${java.version}</source>
                    <target>${build.target}</target>
                </configuration>
            </plugin>
        </plugins>

        <!--Ресурсы-->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>