relevantMembers:
# Список участников проекта, для которых будет проведен анализ погружения
  - asuzdaltsev
  - person1
  - person2
  - person3
  - person4
  #- person5
  
expertisePercentageThreshold: 25

tmsData:
  #Данные TMS
  address: "https://allure-testops.example.org/"
  projectId: 1