relevantMembers:
# Список участников проекта, для которых будет проведен анализ погружения
  - asuzdaltsev
  - vkomisarova
  - ekpetrova
  - ishimkene
  - mzviagina
  #- ekhromova
  #- esmirnova
  
expertisePercentageThreshold: 25

tmsData:
  #Данные TMS
  address: "https://allure-testops.modeus.org/"
  projectId: 1